### ISSUE TITLE
The method 'File.create' has fewer named arguments than those of overridden method 'File.create'

### ISSUE THREAD

**Issue by acuba001** [flutterdata/tutorial#1]
After trying to run the tutorial, I got a `The method 'File.create' has fewer named arguments than those of overridden method 'File.create'` error. A simple `flutter pub upgrade` seemed to fix that issue, but a new error `Null check operator used on a null value` arose. When initializing the repository here:
https://github.com/flutterdata/tutorial/blob/f0504117dd521b23af2c96983330a5e96d4f015d/lib/main.data.dart#L47

After perusing your example in the main [flutter_data](https://github.com/flutterdata/flutter_data/blob/master/example/lib/main.dart) repository, it seems that adding two lines to the `repositoryInitializerProvider` declaration from that example seemed to work.

**Comment by frank06** [comment]
Can you try with the version I just pushed?
